# 🧪 Unidad 7. Extracción automática de terminología

## Identificación de candidatos a términos especializados en un corpus (PLN)

**Idea clave:** detectar automáticamente *términos candidatos* (palabras y expresiones) que son característicos de un **dominio especializado** (p.ej., medicina, derecho, lingüística) comparándolo con un **corpus general**.

## 🎯 Qué vas a aprender

- Conceptos:
  - Frecuencia absoluta y **frecuencia relativa**
  - **N-gramas** (unigramas, bigramas, trigramas)
  - Comparación **corpus especializado vs. corpus general**
- Programación (paso a paso):
  - Tokenización sencilla y limpieza
  - Extracción de n-gramas
  - Filtros por frecuencia y stopwords
  - Ranking de términos candidatos
- Salida:
  - Lista de términos candidatos (top-N)
  - Mini-glosario automático con ejemplos de uso (KWIC)


> En esta unidad priorizamos métodos **transparentes e interpretables** (muy adecuados para Humanidades).

## Contexto profesional

**El encargo: construir un detector de terminología para un equipo de PLN**

Imaginad que formáis parte de un pequeño equipo de PLN contratado por una empresa especializada en traducción, localización y gestión terminológica: LexiData Solutions. La empresa trabaja con clientes institucionales, tecnológicos y científicos. Hasta ahora, muchos de sus glosarios se han elaborado manualmente: una persona experta lee documentos, subraya términos importantes, busca ejemplos y decide qué unidades deben entrar en una base terminológica.

El problema es que el volumen de textos ha crecido demasiado.

Cada semana llegan informes, manuales técnicos, documentos legales, memorias institucionales y páginas web multilingües. El equipo humano ya no puede revisar todo desde cero. Por eso, la dirección ha decidido crear un sistema sencillo de apoyo: una herramienta que ayude a detectar candidatos a término de forma semiautomática.

No se os pide construir una inteligencia artificial gigantesca. No se os pide entrenar un modelo neuronal. El encargo es más concreto y más realista: Diseñar un primer prototipo de extracción terminológica basado en corpus.

El prototipo debe recibir dos conjuntos de textos. Por un lado, un corpus especializado, formado por documentos del dominio que interesa estudiar. Por otro, un corpus general, que servirá como punto de comparación. La hipótesis es sencilla: si una palabra o secuencia aparece mucho en el corpus especializado y poco o nada en el corpus general, probablemente sea característica del dominio.

Ahí empieza vuestro trabajo; vais a ayudar al equipo de traductores de LexiData Solutions, que no quiere una caja negra. Quiere una herramienta interpretable. Necesita saber:

* qué términos candidatos aparecen;
* cuántas veces aparecen;
* si son más frecuentes en el corpus especializado que en el general;
* en qué contextos aparecen;
* cuáles merecen entrar en un glosario preliminar.

Por tanto, el sistema debe producir algo que una persona pueda revisar. No basta con devolver una lista de palabras: hay que justificar por qué esos candidatos son relevantes.

**La misión** 

La tarea de esta Unidad 7 consiste en construir el núcleo del prototipo. El flujo profesional será el siguiente:

* Limpiar los textos: Antes de analizar un corpus, hay que normalizarlo: convertirlo a minúsculas, eliminar signos innecesarios y dividirlo en unidades manejables.

* Tokenizar: El texto se transforma en una secuencia de palabras o tokens. Esta operación parece sencilla, pero es una de las bases de cualquier sistema de PLN.

* Eliminar palabras vacías: Palabras como de, la, el, en o y son muy frecuentes, pero por sí solas aportan poca información terminológica. El sistema debe reducir ese ruido.

* Construir n-gramas: Muchos términos no son una sola palabra, sino combinaciones: traducción automática, modelo de lenguaje, etiquetado morfosintáctico, extracción automática de términos. Por eso no basta con contar palabras aisladas.

* Filtrar por frecuencia mínima: No todo lo que aparece una vez debe considerarse candidato. El prototipo debe permitir decidir cuántas apariciones mínimas necesita una unidad para ser tomada en serio.

* Comparar corpus especializado y corpus general: Aquí entra una idea central: un término no es solo una palabra frecuente, sino una palabra especialmente representativa de un dominio. Para eso usamos una medida de contraste como *weirdness*.

* Validar con contexto: Ningún candidato debe aceptarse sin mirar ejemplos reales. Para eso construiremos concordancias KWIC, que muestran el término en su entorno inmediato.

* Generar un miniglosario: El producto final del encargo será una tabla con candidatos, frecuencias, puntuación de relevancia y ejemplos de uso.

**El conflicto profesional:**

El proyecto no está exento de problemas.

La primera versión del sistema elimina todas las stopwords antes de crear n-gramas. Esto funciona bien para reducir ruido, pero genera efectos secundarios. Por ejemplo:

> Una expresión como *modelo de lenguaje* puede convertirse en --> modelo lenguaje.

> Y una expresión como *lingüística de corpus* puede aparecer como --> lingüística corpus.

El sistema no está “mal”, pero produce candidatos que necesitan interpretación lingüística. Aquí aparece una cuestión profesional importante: las decisiones de preprocesamiento afectan directamente a los resultados.

Por eso el equipo de LexiData os pide no solo ejecutar código, sino pensar como especialistas en PLN. Tendréis que decidir si un candidato es útil, si está deformado por el preprocesamiento, si conviene ajustar el umbral de frecuencia o si es necesario revisar los contextos KWIC antes de aceptarlo.

## 🧭 Estructura del cuaderno

1. **Teoría mínima** (con ejemplos)
2. **Preparación de datos** (dos corpus: general y especializado)
3. **Extracción de candidatos**
4. **Comparación y ranking** (medidas simples y efectivas)
5. **Mini-glosario automático**
6. **Ejercicios** (código + reflexión)
7. **Rúbrica de evaluación**
8. **Recursos adicionales**

## ✅ Resultados de aprendizaje (checklist)

Al final de esta unidad podrás marcar:

- [ ] Distingo **frecuencia absoluta** vs. **relativa**
- [ ] Sé qué es un **n-grama** y para qué sirve en terminología
- [ ] Extraigo candidatos (uni/bi/tri-gramas) de un corpus
- [ ] Comparo con un corpus general para priorizar términos
- [ ] Genero un ranking y lo interpreto críticamente
- [ ] Construyo un mini-glosario automático con ejemplos reales

---
🔎 *Importante:* esto produce **candidatos**. La validación final suele ser humana.

## 1️⃣ ¿Qué es un término y por qué es difícil?

Un **término** es una unidad léxica (una palabra o expresión) que designa un concepto de un **dominio especializado**.

Ejemplos (dominio: PLN):
- *etiquetado morfosintáctico*
- *modelo de lenguaje*
- *tokenización*

### ¿Por qué la extracción automática no es trivial?
Porque hay “ruido”:
- Palabras frecuentes que **no** son términos: *de, la, y, tiene…*
- Palabras frecuentes en general que aparecen también en el dominio: *sistema, análisis…*
- Expresiones multi-palabra que sí son términos: *red neuronal*, *aprendizaje supervisado*

### Estrategia típica en PLN (interpretables)
1. Generar **candidatos** (tokens y n-gramas)
2. Filtrar (frecuencia mínima, stopwords, longitud, etc.)
3. Rankear (¿qué es más “propio” del dominio?)
4. Validar (humano / experto / tarea downstream)

## 2️⃣ Frecuencia absoluta y relativa, y comparación entre corpus

### Frecuencia absoluta
Cuántas veces aparece una unidad:
- `freq("tokenización") = 25`

### Frecuencia relativa
Frecuencia ajustada por el tamaño del corpus (muy importante):
- `freq_rel = freq / total_tokens`
- Por ejemplo, “tokenización” puede aparecer 25 veces en un corpus de 10.000 tokens (0.25%)
  y 5 veces en otro de 100.000 tokens (0.005%).  
  **Comparar absolutos sin normalizar engaña.**

### Comparación corpus general vs. especializado
Buscamos unidades que:
- aparezcan con **frecuencia relativamente alta en el corpus especializado**
- y/o estén **mucho menos presentes en el corpus general**

Esto da lugar a medidas de “termhood” (carácter terminológico).
En este cuaderno implementaremos una medida simple y muy usada en docencia:

**Weirdness (raridad relativa):**
\[
weirdness(t) = \frac{f_{esp}(t)/N_{esp}}{f_{gen}(t)/N_{gen} + \epsilon}
\]
- Si es grande ⇒ el término es mucho más típico del especializado.
- `ε` evita dividir entre 0.

## 3️⃣ Plan práctico del cuaderno

Vamos a:
1. Preparar dos corpus:
   - `corpus_especializado`: textos del dominio (p.ej., fragmentos sobre PLN)
   - `corpus_general`: textos generales (p.ej., noticias / Wikipedia general / textos variados)
2. Tokenizar y limpiar (minúsculas, puntuación, números, etc.)
3. Extraer:
   - unigramas (1 palabra)
   - bigramas (2 palabras)
   - trigramas (3 palabras)
4. Filtrar candidatos
5. Calcular métricas y rankear
6. Generar un mini-glosario con:
   - término
   - score
   - ejemplos de contexto (KWIC)


> 💡 En corpus pequeños los resultados pueden variar mucho: ¡es normal!

### 3.1. Preparación del entorno

In [1]:
import re
from collections import Counter, defaultdict
from math import log
from typing import List, Tuple, Dict

import pandas as pd

> Nota sobre dependencias:

Este cuaderno evita depender de herramientas pesadas para que el código sea:
- fácil de entender,
- fácil de ejecutar en cualquier entorno,
- ideal para alumnado de Humanidades.

Si quieres una versión “pro” con análisis morfosintáctico (PoS) usando spaCy,
dejamos una ampliación al final.

### 3.2. Corpus

📌 En clase trabajaremos con textos de ejemplo (pequeños). Después, en ejercicios, los sustituirás por textos reales.

✅ Recomendación: que ambos corpus tengan **tamaño parecido** para comparar mejor.

In [2]:
corpus_especializado = [
    """
    La tokenización es un paso fundamental en el procesamiento del lenguaje natural.
    En PLN, la tokenización permite dividir el texto en unidades básicas llamadas tokens.
    Un modelo de lenguaje necesita una tokenización coherente para entrenarse correctamente.
    """,

    """
    Un modelo de lenguaje se entrena a partir de grandes corpus de texto.
    Los modelos de lenguaje actuales utilizan redes neuronales profundas.
    El entrenamiento de un modelo de lenguaje requiere muchos datos y recursos computacionales.
    """,

    """
    La traducción automática es una de las aplicaciones más importantes del PLN.
    La traducción automática neuronal ha mejorado la calidad de las traducciones.
    Los sistemas de traducción automática se evalúan mediante métricas automáticas.
    """,

    """
    En la traducción automática se utilizan corpus paralelos.
    Los corpus paralelos contienen textos alineados en dos lenguas.
    La calidad del corpus es clave para un sistema de traducción automática.
    """,

    """
    El etiquetado morfosintáctico asigna una categoría gramatical a cada token.
    El etiquetado morfosintáctico es una tarea clásica del PLN.
    Muchos sistemas de PLN utilizan el etiquetado morfosintáctico como paso previo.
    """,

    """
    Los embeddings representan palabras como vectores numéricos.
    Los embeddings capturan relaciones semánticas entre palabras.
    Los modelos de lenguaje modernos utilizan embeddings contextuales.
    """,

    """
    Un corpus especializado contiene textos de un dominio concreto.
    La comparación entre un corpus general y un corpus especializado permite extraer terminología.
    La terminología es fundamental para tareas de PLN aplicado.
    """,

    """
    La extracción automática de términos es una tarea importante en terminología computacional.
    La extracción de términos se basa en frecuencias y comparación de corpus.
    La extracción automática de términos produce candidatos que deben validarse.
    """,

    """
    En PLN, los n-gramas permiten detectar expresiones frecuentes.
    Los n-gramas de dos palabras y los n-gramas de tres palabras son útiles para detectar términos.
    El análisis de n-gramas es una técnica común en lingüística computacional.
    """,

    """
    La evaluación de sistemas de PLN es un aspecto fundamental.
    En traducción automática se utilizan métricas como BLEU para la evaluación.
    La evaluación automática no siempre refleja la calidad lingüística real.
    """
]

corpus_general = [
    """
    El gobierno anunció nuevas medidas económicas para afrontar la crisis.
    La situación económica preocupa a los ciudadanos.
    El mercado laboral muestra signos de recuperación y estabilidad.
    """,

    """
    La tecnología avanza rápidamente y transforma distintos sectores.
    Las empresas invierten en innovación para mejorar su competitividad.
    La digitalización cambia la forma de trabajar y comunicarse.
    """,

    """
    La educación es un pilar fundamental del desarrollo social.
    Los sistemas educativos deben adaptarse a los cambios actuales.
    La formación continua es clave para el futuro profesional.
    """,

    """
    El deporte es seguido por millones de personas en todo el mundo.
    Los resultados del fin de semana generaron gran expectación.
    El equipo local consiguió una victoria importante.
    """,

    """
    La salud pública es una prioridad para los gobiernos.
    Los sistemas sanitarios enfrentan nuevos desafíos.
    La prevención y la investigación médica son fundamentales.
    """,

    """
    La cultura y el arte forman parte de la identidad de una sociedad.
    La literatura y el cine reflejan cambios históricos y sociales.
    Los eventos culturales atraen a numerosos visitantes.
    """,

    """
    El medio ambiente ocupa un lugar central en el debate actual.
    El cambio climático afecta a diferentes regiones del planeta.
    La protección de los ecosistemas es una responsabilidad colectiva.
    """,

    """
    El transporte público mejora la movilidad en las ciudades.
    Las infraestructuras son esenciales para el desarrollo económico.
    La planificación urbana influye en la calidad de vida.
    """,

    """
    El turismo es una fuente importante de ingresos.
    Muchas ciudades dependen del turismo cultural y gastronómico.
    La sostenibilidad es un reto para el sector turístico.
    """,

    """
    La política internacional influye en la economía global.
    Los acuerdos entre países afectan al comercio y a la diplomacia.
    La cooperación internacional es clave para la estabilidad.
    """
]

len(corpus_especializado), len(corpus_general)

(10, 10)

#### Cuando tengas tu corpus real

Puedes reemplazar `corpus_especializado` y `corpus_general` por:
- listas de textos leídos desde archivos `.txt`
- columnas de un `.csv`
- o resultados de una extracción web (con cuidado ético y legal)

En docencia es común:
- **especializado**: artículos de un área, manuales, apuntes, normativa…
- **general**: noticias, Wikipedia general, narrativa, blogs variados…

### 3.3. Tokenización y lematización

Aquí haremos una tokenización **simple y transparente**:
- pasamos a minúsculas
- quitamos URLs
- eliminamos signos/puntuación/números
- dividimos por espacios

> 🧠 No es “perfecto”, pero es ideal para entender el proceso.

In [3]:
def simple_tokenize(text: str) -> List[str]:
    """
    Tokenizador simple:
    - pasa a minúsculas
    - elimina URLs
    - mantiene letras con tildes/ñ (rango Unicode básico latino)
    - convierte todo lo demás en espacios
    - divide por espacios
    - filtra tokens muy cortos (opcional)
    
    Nota didáctica:
    Esto NO es perfecto, pero es transparente y suficiente para practicar
    extracción terminológica basada en frecuencias.
    """
    text = text.lower()
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)  # quita URLs
    
    # Reemplazamos por espacio cualquier cosa que NO sea letra (incluye tildes) o espacio
    text = re.sub(r"[^a-záéíóúüñ\s]", " ", text)
    
    # Colapsa espacios múltiples
    text = re.sub(r"\s+", " ", text).strip()
    
    tokens = text.split(" ")
    
    # Filtramos tokens muy cortos (p.ej. "a", "y" se filtran después con stopwords)
    tokens = [t for t in tokens if len(t) >= 2]
    return tokens


# Probamos el tokenizador con un ejemplo pequeño
example = "La tokenización en PLN: modelos, embeddings y n-gramas (2025)."
simple_tokenize(example)

['la', 'tokenización', 'en', 'pln', 'modelos', 'embeddings', 'gramas']

### 3.4. Stopwords

Las **stopwords** son palabras muy frecuentes con poco contenido terminológico:
- artículos, preposiciones, conjunciones…

En extracción de términos, si no filtramos stopwords, el ranking se llena de:
- *de, la, en, y, que, los…*

Aquí usaremos una lista básica en español (editable).

> 📌 OJO: en terminología real, a veces interesa conservar “de” dentro de expresiones
> (véase la ampliación al final).

In [4]:
# Lista básica (puedes ampliarla según el dominio)
STOPWORDS_ES = {
    "de","la","que","el","en","y","a","los","del","se","las","por","un","para",
    "con","no","una","su","al","lo","como","más","pero","sus","le","ya","o",
    "este","sí","porque","esta","entre","cuando","muy","sin","sobre","también",
    "me","hasta","hay","donde","quien","desde","todo","nos","durante","todos",
    "uno","les","ni","contra","otros","ese","eso","ante","ellos","e","esto",
    "mí","antes","algunos","qué","unos","yo","otro","otras","otra","él","tanto",
    "esa","estos","mucho","quienes","nada","muchos","cual","poco","ella","estar",
    "estas","algunas","algo","nosotros","mi","mis","tú","te","ti","tu","tus"
}

def remove_stopwords(tokens: List[str], stopwords=STOPWORDS_ES) -> List[str]:
    return [t for t in tokens if t not in stopwords]

# Ejemplo rápido
remove_stopwords(simple_tokenize("La tokenización es un paso fundamental en PLN."))

['tokenización', 'es', 'paso', 'fundamental', 'pln']

### 3.5. Preprocesado del corpus

In [5]:
def preprocess_corpus(corpus: List[str]) -> List[str]:
    """
    Convierte una lista de textos en una lista plana de tokens:
    - tokeniza
    - elimina stopwords
    """
    all_tokens = []
    for doc in corpus:
        toks = simple_tokenize(doc)
        toks = remove_stopwords(toks)
        all_tokens.extend(toks)
    return all_tokens

tokens_esp = preprocess_corpus(corpus_especializado)
tokens_gen = preprocess_corpus(corpus_general)

len(tokens_esp), len(tokens_gen), tokens_esp[:20]

(202,
 164,
 ['tokenización',
  'es',
  'paso',
  'fundamental',
  'procesamiento',
  'lenguaje',
  'natural',
  'pln',
  'tokenización',
  'permite',
  'dividir',
  'texto',
  'unidades',
  'básicas',
  'llamadas',
  'tokens',
  'modelo',
  'lenguaje',
  'necesita',
  'tokenización'])

### 3.6. Extracción de n-gramas

Muchos términos importantes son **expresiones**:
- *modelo de lenguaje*
- *traducción automática*
- *red neuronal*

Un **n-grama** es una secuencia de `n` tokens consecutivos:
- unigramas: `n=1` → “tokenización”
- bigramas: `n=2` → “modelo lenguaje”
- trigramas: `n=3` → “traducción automática neuronal”

> Nota: al quitar stopwords, “modelo de lenguaje” se convierte en “modelo lenguaje”.

> Esto es normal en pipelines simples. En versión ampliada veremos cómo conservar “de”.

In [6]:
def get_ngrams(tokens: List[str], n: int) -> List[Tuple[str, ...]]:
    """
    Devuelve una lista de n-gramas como tuplas.
    Ejemplo: tokens = ["modelo","lenguaje","grande"], n=2
    -> [("modelo","lenguaje"), ("lenguaje","grande")]
    """
    return [tuple(tokens[i:i+n]) for i in range(len(tokens)-n+1)]

# Ejemplo
get_ngrams(["modelo","lenguaje","grande"], 2)

[('modelo', 'lenguaje'), ('lenguaje', 'grande')]

### 3.7. Recuento frecuencia n-gramas

In [7]:
def count_ngrams(tokens: List[str], n: int) -> Counter:
    """
    Cuenta frecuencias de n-gramas y devuelve Counter:
    Counter({('modelo','lenguaje'): 3, ...})
    """
    ngrams = get_ngrams(tokens, n)
    return Counter(ngrams)

freq1_esp = count_ngrams(tokens_esp, 1)
freq2_esp = count_ngrams(tokens_esp, 2)
freq3_esp = count_ngrams(tokens_esp, 3)

freq1_gen = count_ngrams(tokens_gen, 1)
freq2_gen = count_ngrams(tokens_gen, 2)
freq3_gen = count_ngrams(tokens_gen, 3)

freq2_esp.most_common(10)

[(('traducción', 'automática'), 6),
 (('modelo', 'lenguaje'), 3),
 (('etiquetado', 'morfosintáctico'), 3),
 (('modelos', 'lenguaje'), 2),
 (('automática', 'utilizan'), 2),
 (('corpus', 'paralelos'), 2),
 (('es', 'tarea'), 2),
 (('sistemas', 'pln'), 2),
 (('corpus', 'especializado'), 2),
 (('comparación', 'corpus'), 2)]

### 3.8. Filtrado de candidatos y conversión a texto

Antes de rankear, filtramos “ruido”. Reglas típicas:
- **frecuencia mínima**: si aparece 1 vez, suele ser ruido (depende del tamaño del corpus)
- **longitud mínima**: evitar tokens demasiado cortos
- **caracteres raros**: ya los eliminamos en limpieza
- (opcional) **listas negras**: palabras muy generales del dominio (*sistema, análisis…*) si molestan

En este cuaderno aplicaremos filtros simples:
- unigramas: frecuencia ≥ 2
- bigramas/trigramas: frecuencia ≥ 2 (en corpus reales quizá ≥ 3 o ≥ 5)

In [8]:
def ngram_to_text(ng: Tuple[str, ...]) -> str:
    """Convierte ('modelo','lenguaje') -> 'modelo lenguaje'"""
    return " ".join(ng)

def filter_by_min_freq(counter: Counter, min_freq: int) -> Dict[str, int]:
    """
    Filtra un Counter de n-gramas por frecuencia mínima y devuelve dict {texto: freq}.
    """
    out = {}
    for ng, f in counter.items():
        if f >= min_freq:
            out[ngram_to_text(ng)] = f
    return out

cand1_esp = filter_by_min_freq(freq1_esp, min_freq=2)
cand2_esp = filter_by_min_freq(freq2_esp, min_freq=2)
cand3_esp = filter_by_min_freq(freq3_esp, min_freq=2)

len(cand1_esp), len(cand2_esp), len(cand3_esp)

(35, 12, 2)

### 3.9. Frecuencia relativa

**Frecuencia relativa: normalizar por tamaño del corpus**

Si un corpus tiene más tokens, sus frecuencias absolutas serán mayores aunque el fenómeno sea el mismo.

Definimos:
- `N_esp = total tokens (tamaño) del corpus especializado`
- `N_gen = total tokens (tamaño) del corpus general`

Y la frecuencia relativa:
- `rel = freq / N`

Esto permite comparar.

In [9]:
N_esp = len(tokens_esp)
N_gen = len(tokens_gen)

def rel_freq(freq: int, N: int) -> float:
    return freq / N if N > 0 else 0.0

# ejemplo
term = "tokenización"
freq_term = cand1_esp.get(term, 0)
rel_freq(freq_term, N_esp), freq_term

(0.01485148514851485, 3)

### 3.10. Raking por *weirdness*

**Ranking por “Weirdness” (comparación especializado vs. general)**:

*Weirdness* aumenta si:
- el término es relativamente frecuente en el corpus especializado
- y relativamente raro en el corpus general

Usamos:
\[
weirdness(t) = \frac{f_{esp}(t)/N_{esp}}{f_{gen}(t)/N_{gen} + \epsilon}
\]

**Advertencia didáctica:**
- Si el término no aparece en el corpus general, el denominador sería 0.  
  Por eso añadimos `ε` (un número muy pequeño).
- En corpora muy pequeños (como nuestro ejemplo), los rankings pueden ser inestables.
  En corpora reales mejora mucho.

In [11]:
def compute_weirdness(
    cand_esp: Dict[str, int],
    freq_gen_counter: Counter,
    N_esp: int,
    N_gen: int,
    epsilon: float = 1e-9
) -> pd.DataFrame:
    """
    Calcula weirdness para un conjunto de candidatos (texto -> freq en especializado).
    freq_gen_counter es un Counter de n-gramas del corpus general (tuplas).
    
    Devuelve un DataFrame con:
    - term
    - freq_esp, rel_esp
    - freq_gen, rel_gen
    - weirdness
    """
    rows = []
    # Construimos un diccionario rápido para freq general en formato texto
    gen_text_freq = {ngram_to_text(k): v for k, v in freq_gen_counter.items()}
    
    for term, f_esp in cand_esp.items():
        f_gen = gen_text_freq.get(term, 0)
        r_esp = rel_freq(f_esp, N_esp)
        r_gen = rel_freq(f_gen, N_gen)
        w = r_esp / (r_gen + epsilon)
        rows.append((term, f_esp, r_esp, f_gen, r_gen, w))
    
    df = pd.DataFrame(rows, columns=["term","freq_esp","rel_esp","freq_gen","rel_gen","weirdness"])
    df = df.sort_values("weirdness", ascending=False).reset_index(drop=True)
    return df

df_uni = compute_weirdness(cand1_esp, freq1_gen, N_esp, N_gen)
df_bi  = compute_weirdness(cand2_esp, freq2_gen, N_esp, N_gen)
df_tri = compute_weirdness(cand3_esp, freq3_gen, N_esp, N_gen)

df_bi.head(10)

,term,freq_esp,rel_esp,freq_gen,rel_gen,weirdness
0,traducción automática,6,0.029703,0,0.0,2.970297e+07
1,modelo lenguaje,3,0.014851,0,0.0,1.485149e+07
2,etiquetado morfosintáctico,3,0.014851,0,0.0,1.485149e+07
3,modelos lenguaje,2,0.009901,0,0.0,9.900990e+06
4,automática utilizan,2,0.009901,0,0.0,9.900990e+06
5,corpus paralelos,2,0.009901,0,0.0,9.900990e+06
6,es tarea,2,0.009901,0,0.0,9.900990e+06
7,sistemas pln,2,0.009901,0,0.0,9.900990e+06
8,corpus especializado,2,0.009901,0,0.0,9.900990e+06
9,comparación corpus,2,0.009901,0,0.0,9.900990e+06

### 3.11. Interpretación de los resultados

Mira estas columnas:
- `freq_esp`: cuántas veces aparece en el corpus especializado
- `rel_esp`: su proporción (normalizada)
- `freq_gen`, `rel_gen`: lo mismo en el corpus general
- `weirdness`: “lo típico” que es del dominio (según estos datos)

**Consejo:**
- No te quedes solo con el score. Revisa manualmente el top-20.
- Un buen término candidato suele ser:
  - informativo
  - relativamente estable (no un nombre propio aislado)
  - útil como entrada de glosario

### 3.12. Unificar candidatos de distintos n

Unificamos unigramas, bigramas y trigramas, y sacamos top candidatos.

Aquí creamos una tabla única con:
- término
- tamaño (n)
- weirdness
- frecuencias

In [12]:
def add_ngram_size(df: pd.DataFrame, n: int) -> pd.DataFrame:
    df = df.copy()
    df["n"] = n
    return df

df_all = pd.concat([
    add_ngram_size(df_uni, 1),
    add_ngram_size(df_bi, 2),
    add_ngram_size(df_tri, 3),
], ignore_index=True)

# Un criterio simple: quedarnos con los mejores por weirdness
df_all_sorted = df_all.sort_values("weirdness", ascending=False).reset_index(drop=True)
df_all_sorted.head(20)

,term,freq_esp,rel_esp,freq_gen,rel_gen,weirdness,n
0,automática,9,0.044554,0,0.0,4.455446e+07,1
1,corpus,8,0.039604,0,0.0,3.960396e+07,1
2,pln,7,0.034653,0,0.0,3.465347e+07,1
3,traducción,6,0.029703,0,0.0,2.970297e+07,1
4,lenguaje,6,0.029703,0,0.0,2.970297e+07,1
5,traducción automática,6,0.029703,0,0.0,2.970297e+07,2
6,utilizan,5,0.024752,0,0.0,2.475248e+07,1
7,gramas,4,0.019802,0,0.0,1.980198e+07,1
8,términos,4,0.019802,0,0.0,1.980198e+07,1
9,palabras,4,0.019802,0,0.0,1.980198e+07,1
10,tokenización,3,0.014851,0,0.0,1.485149e+07,1
11,etiquetado,3,0.014851,0,0.0,1.485149e+07,1
12,morfosintáctico,3,0.014851,0,0.0,1.485149e+07,1
13,extracción,3,0.014851,0,0.0,1.485149e+07,1
14,terminología,3,0.014851,0,0.0,1.485149e+07,1
15,modelo,3,0.014851,0,0.0,1.485149e+07,1
16,embeddings,3,0.014851,0,0.0,1.485149e+07,1
17,evaluación,3,0.014851,0,0.0,1.485149e+07,1
18,modelo lenguaje,3,0.014851,0,0.0,1.485149e+07,2
19,etiquetado morfosintáctico,3,0.014851,0,0.0,1.485149e+07,2

Para verlo bonito:

In [13]:
# En el pipeline explicativo, ya tienes df_uni y df_bi (min_freq=2)
# así que muéstralos directamente:

print("Top-10 unigramas (min_freq=2)")
display(df_uni.head(10))

print("\nTop-10 bigramas (min_freq=2)")
display(df_bi.head(10))

Top-10 unigramas (min_freq=2)

           term  freq_esp   rel_esp  freq_gen  rel_gen     weirdness
0    automática         9  0.044554         0      0.0  4.455446e+07
1        corpus         8  0.039604         0      0.0  3.960396e+07
2           pln         7  0.034653         0      0.0  3.465347e+07
3    traducción         6  0.029703         0      0.0  2.970297e+07
4      lenguaje         6  0.029703         0      0.0  2.970297e+07
5      utilizan         5  0.024752         0      0.0  2.475248e+07
6      términos         4  0.019802         0      0.0  1.980198e+07
7        gramas         4  0.019802         0      0.0  1.980198e+07
8      palabras         4  0.019802         0      0.0  1.980198e+07
9  tokenización         3  0.014851         0      0.0  1.485149e+07

Top-10 bigramas (min_freq=2)

,term,freq_esp,rel_esp,freq_gen,rel_gen,weirdness
0,traducción automática,6,0.029703,0,0.0,2.970297e+07
1,modelo lenguaje,3,0.014851,0,0.0,1.485149e+07
2,etiquetado morfosintáctico,3,0.014851,0,0.0,1.485149e+07
3,modelos lenguaje,2,0.009901,0,0.0,9.900990e+06
4,automática utilizan,2,0.009901,0,0.0,9.900990e+06
5,corpus paralelos,2,0.009901,0,0.0,9.900990e+06
6,es tarea,2,0.009901,0,0.0,9.900990e+06
7,sistemas pln,2,0.009901,0,0.0,9.900990e+06
8,corpus especializado,2,0.009901,0,0.0,9.900990e+06
9,comparación corpus,2,0.009901,0,0.0,9.900990e+06

### 3.13. Refinamiento para mejorar la calidad

**Refinamiento: heurísticas para mejorar calidad**

En terminología, además de la comparación con corpus general, se suelen aplicar heurísticas:
- Evitar términos demasiado genéricos (lista negra)
- Penalizar cadenas que comienzan/terminan con palabras poco informativas
- Priorizar n-gramas que se repiten en contextos variados

Aquí añadimos una heurística sencilla:
- eliminar candidatos que contengan solo palabras “muy generales” (editable)

> Esto es *ingeniería lingüística* ligera: muy útil en Humanidades porque es interpretable.

In [14]:
BLACKLIST = {
    "paso", "importante", "sistema", "cantidad", "texto", "comparación", "corpus",
    "uso", "métricas"  # ajusta según tu dominio
}

def contains_blacklisted(term: str, blacklist=BLACKLIST) -> bool:
    toks = term.split()
    return all(t in blacklist for t in toks)

df_clean = df_all_sorted[~df_all_sorted["term"].apply(contains_blacklisted)].reset_index(drop=True)
df_clean.head(20)

,term,freq_esp,rel_esp,freq_gen,rel_gen,weirdness,n
0,automática,9,0.044554,0,0.0,4.455446e+07,1
1,pln,7,0.034653,0,0.0,3.465347e+07,1
2,traducción,6,0.029703,0,0.0,2.970297e+07,1
3,lenguaje,6,0.029703,0,0.0,2.970297e+07,1
4,traducción automática,6,0.029703,0,0.0,2.970297e+07,2
5,utilizan,5,0.024752,0,0.0,2.475248e+07,1
6,gramas,4,0.019802,0,0.0,1.980198e+07,1
7,términos,4,0.019802,0,0.0,1.980198e+07,1
8,palabras,4,0.019802,0,0.0,1.980198e+07,1
9,tokenización,3,0.014851,0,0.0,1.485149e+07,1
10,etiquetado,3,0.014851,0,0.0,1.485149e+07,1
11,morfosintáctico,3,0.014851,0,0.0,1.485149e+07,1
12,extracción,3,0.014851,0,0.0,1.485149e+07,1
13,terminología,3,0.014851,0,0.0,1.485149e+07,1
14,modelo,3,0.014851,0,0.0,1.485149e+07,1
15,embeddings,3,0.014851,0,0.0,1.485149e+07,1
16,evaluación,3,0.014851,0,0.0,1.485149e+07,1
17,modelo lenguaje,3,0.014851,0,0.0,1.485149e+07,2
18,etiquetado morfosintáctico,3,0.014851,0,0.0,1.485149e+07,2
19,dos,2,0.009901,0,0.0,9.900990e+06,1

### 3.14. Miniglosario automático

Un “miniglosario” útil puede incluir:
- término candidato
- score (para justificar por qué aparece)
- ejemplos de concordancia (KWIC: *keyword in context*). ✅ KWIC ayuda a validar si el candidato “tiene sentido” como término.

KWIC muestra el término con palabras alrededor, por ejemplo:
- “… la tokenización es un paso …”
- “… métricas como BLEU …”

Esto ayuda a:
- entender significado por contexto
- verificar si realmente es un término

In [15]:
def kwic(tokens: List[str], term_tokens: List[str], window: int = 5, max_examples: int = 5) -> List[str]:
    """
    Devuelve ejemplos KWIC para term_tokens dentro de una lista de tokens.
    - window: número de tokens a izquierda y derecha
    - max_examples: máximo de ejemplos a devolver
    
    Nota: buscamos coincidencia exacta de secuencia.
    """
    examples = []
    n = len(term_tokens)
    for i in range(len(tokens) - n + 1):
        if tokens[i:i+n] == term_tokens:
            left = " ".join(tokens[max(0, i-window):i])
            hit  = " ".join(tokens[i:i+n])
            right= " ".join(tokens[i+n:i+n+window])
            examples.append(f"{left}  >>{hit}<<  {right}".strip())
            if len(examples) >= max_examples:
                break
    return examples

# Probamos con un término
kwic(tokens_esp, ["modelo", "lenguaje"], window=4, max_examples=10)

['unidades básicas llamadas tokens  >>modelo lenguaje<<  necesita tokenización coherente entrenarse',
 'tokenización coherente entrenarse correctamente  >>modelo lenguaje<<  entrena partir grandes corpus',
 'redes neuronales profundas entrenamiento  >>modelo lenguaje<<  requiere datos recursos computacionales']

**Visualización "bonita" del miniglosario**

En una clase, es habitual presentar:
- término
- score
- 2–3 ejemplos KWIC

La siguiente celda imprime una versión legible.

In [16]:
def build_mini_glossary(df_ranked: pd.DataFrame, tokens_esp: List[str], top_n: int = 15) -> pd.DataFrame:
    rows = []
    for _, row in df_ranked.head(top_n).iterrows():
        term = row["term"]
        term_tokens = term.split()
        examples = kwic(tokens_esp, term_tokens, window=5, max_examples=3)
        rows.append({
            "term": term,
            "n": row["n"],
            "weirdness": row["weirdness"],
            "freq_esp": row["freq_esp"],
            "freq_gen": row["freq_gen"],
            "kwic_examples": examples
        })
    return pd.DataFrame(rows)

def print_glossary(glossary_df: pd.DataFrame):
    for i, row in glossary_df.iterrows():
        print(f"\n📌 #{i+1}  {row['term']}  (n={row['n']})")
        print(f"   🧮 weirdness={row['weirdness']:.2f} | esp={row['freq_esp']} | gen={row['freq_gen']}")
        if row["kwic_examples"]:
            print("   🔎 Ejemplos (KWIC):")
            for ex in row["kwic_examples"]:
                print("   -", ex)
        else:
            print("   ⚠️ Sin ejemplos KWIC (revisar filtros)")

glossary = build_mini_glossary(df_all_sorted, tokens_esp, top_n=15)
print_glossary(glossary)

📌 #1  automática  (n=1)
   🧮 weirdness=44554455.45 | esp=9 | gen=0
   🔎 Ejemplos (KWIC):
   - requiere datos recursos computacionales traducción  >>automática<<  es aplicaciones importantes pln traducción
   - es aplicaciones importantes pln traducción  >>automática<<  neuronal ha mejorado calidad traducciones
   - mejorado calidad traducciones sistemas traducción  >>automática<<  evalúan mediante métricas automáticas traducción

📌 #2  corpus  (n=1)
   🧮 weirdness=39603960.40 | esp=8 | gen=0
   🔎 Ejemplos (KWIC):
   - modelo lenguaje entrena partir grandes  >>corpus<<  texto modelos lenguaje actuales utilizan
   - métricas automáticas traducción automática utilizan  >>corpus<<  paralelos corpus paralelos contienen textos
   - traducción automática utilizan corpus paralelos  >>corpus<<  paralelos contienen textos alineados dos

📌 #3  pln  (n=1)
   🧮 weirdness=34653465.35 | esp=7 | gen=0
   🔎 Ejemplos (KWIC):
   - paso fundamental procesamiento lenguaje natural  >>pln<<  tokenización permite dividir texto unidades
   - traducción automática es aplicaciones importantes  >>pln<<  traducción automática neuronal ha mejorado
   - etiquetado morfosintáctico es tarea clásica  >>pln<<  sistemas pln utilizan etiquetado morfosintáctico

📌 #4  traducción  (n=1)
   🧮 weirdness=29702970.30 | esp=6 | gen=0
   🔎 Ejemplos (KWIC):
   - lenguaje requiere datos recursos computacionales  >>traducción<<  automática es aplicaciones importantes pln
   - automática es aplicaciones importantes pln  >>traducción<<  automática neuronal ha mejorado calidad
   - ha mejorado calidad traducciones sistemas  >>traducción<<  automática evalúan mediante métricas automáticas

📌 #5  lenguaje  (n=1)
   🧮 weirdness=29702970.30 | esp=6 | gen=0
   🔎 Ejemplos (KWIC):
   - tokenización es paso fundamental procesamiento  >>lenguaje<<  natural pln tokenización permite dividir
   - unidades básicas llamadas tokens modelo  >>lenguaje<<  necesita tokenización coherente entrenarse correctamente
   - tokenización coherente entrenarse correctamente modelo  >>lenguaje<<  entrena partir grandes corpus texto

📌 #6  traducción automática  (n=2)
   🧮 weirdness=29702970.30 | esp=6 | gen=0
   🔎 Ejemplos (KWIC):
   - lenguaje requiere datos recursos computacionales  >>traducción automática<<  es aplicaciones importantes pln traducción
   - automática es aplicaciones importantes pln  >>traducción automática<<  neuronal ha mejorado calidad traducciones
   - ha mejorado calidad traducciones sistemas  >>traducción automática<<  evalúan mediante métricas automáticas traducción

📌 #7  utilizan  (n=1)
   🧮 weirdness=24752475.25 | esp=5 | gen=0
   🔎 Ejemplos (KWIC):
   - corpus texto modelos lenguaje actuales  >>utilizan<<  redes neuronales profundas entrenamiento modelo
   - mediante métricas automáticas traducción automática  >>utilizan<<  corpus paralelos corpus paralelos contienen
   - tarea clásica pln sistemas pln  >>utilizan<<  etiquetado morfosintáctico paso previo embeddings

📌 #8  gramas  (n=1)
   🧮 weirdness=19801980.20 | esp=4 | gen=0
   🔎 Ejemplos (KWIC):
   - produce candidatos deben validarse pln  >>gramas<<  permiten detectar expresiones frecuentes gramas
   - gramas permiten detectar expresiones frecuentes  >>gramas<<  dos palabras gramas tres palabras
   - expresiones frecuentes gramas dos palabras  >>gramas<<  tres palabras son útiles detectar

📌 #9  términos  (n=1)
   🧮 weirdness=19801980.20 | esp=4 | gen=0
   🔎 Ejemplos (KWIC):
   - tareas pln aplicado extracción automática  >>términos<<  es tarea importante terminología computacional
   - tarea importante terminología computacional extracción  >>términos<<  basa frecuencias comparación corpus extracción
   - frecuencias comparación corpus extracción automática  >>términos<<  produce candidatos deben validarse pln

📌 #10  palabras  (n=1)
   🧮 weirdness=19801980.20 | esp=4 | gen=0
   🔎 Ejemplos (KWIC):
   - morfosintáctico paso previo embeddings representan  >>palabras<<  vectores numéricos embeddings capturan relaciones
   - numéricos embeddings capturan relaciones semánticas  >>palabras<<  modelos lenguaje modernos utilizan embeddings
   - detectar expresiones frecuentes gramas dos  >>palabras<<  gramas tres palabras son útiles

📌 #11  tokenización  (n=1)
   🧮 weirdness=14851485.15 | esp=3 | gen=0
   🔎 Ejemplos (KWIC):
   - >>tokenización<<  es paso fundamental procesamiento lenguaje
   - fundamental procesamiento lenguaje natural pln  >>tokenización<<  permite dividir texto unidades básicas
   - llamadas tokens modelo lenguaje necesita  >>tokenización<<  coherente entrenarse correctamente modelo lenguaje

📌 #12  etiquetado  (n=1)
   🧮 weirdness=14851485.15 | esp=3 | gen=0
   🔎 Ejemplos (KWIC):
   - es clave sistema traducción automática  >>etiquetado<<  morfosintáctico asigna categoría gramatical cada
   - asigna categoría gramatical cada token  >>etiquetado<<  morfosintáctico es tarea clásica pln
   - clásica pln sistemas pln utilizan  >>etiquetado<<  morfosintáctico paso previo embeddings representan

📌 #13  morfosintáctico  (n=1)
   🧮 weirdness=14851485.15 | esp=3 | gen=0
   🔎 Ejemplos (KWIC):
   - clave sistema traducción automática etiquetado  >>morfosintáctico<<  asigna categoría gramatical cada token
   - categoría gramatical cada token etiquetado  >>morfosintáctico<<  es tarea clásica pln sistemas
   - pln sistemas pln utilizan etiquetado  >>morfosintáctico<<  paso previo embeddings representan palabras

📌 #14  extracción  (n=1)
   🧮 weirdness=14851485.15 | esp=3 | gen=0
   🔎 Ejemplos (KWIC):
   - es fundamental tareas pln aplicado  >>extracción<<  automática términos es tarea importante
   - es tarea importante terminología computacional  >>extracción<<  términos basa frecuencias comparación corpus
   - términos basa frecuencias comparación corpus  >>extracción<<  automática términos produce candidatos deben

📌 #15  terminología  (n=1)
   🧮 weirdness=14851485.15 | esp=3 | gen=0
   🔎 Ejemplos (KWIC):
   - general corpus especializado permite extraer  >>terminología<<  terminología es fundamental tareas pln
   - corpus especializado permite extraer terminología  >>terminología<<  es fundamental tareas pln aplicado
   - automática términos es tarea importante  >>terminología<<  computacional extracción términos basa frecuencias

## 🧾 Resumen del *pipeline*

1. **Preprocesamiento**
   - minúsculas, limpieza, tokenización
   - stopwords
2. **Candidatos**
   - unigramas, bigramas, trigramas
3. **Filtrado**
   - frecuencia mínima
4. **Comparación entre corpus**
   - frecuencia relativa
   - weirdness (típico del dominio)
5. **Salida**
   - ranking top-N
   - mini-glosario con KWIC

**Resultado esperado:** una lista priorizada de expresiones que un humano puede validar como terminología.

## 🧾 Actividades propuestas

## 📚 4. Recursos adicionales

Los siguientes recursos permiten **profundizar** en los fundamentos teóricos de la terminología, en los **métodos automáticos basados en corpus** y en su aplicación en PLN. Se incluyen lecturas introductorias, artículos especializados y materiales audiovisuales.

---

### 📖 1. Terminología: fundamentos teóricos (imprescindibles)

#### 🔹 Cabré, M. Teresa
- **Cabré, M. T. (1999). *La terminología: representación y comunicación*.**  
  Barcelona: Institut Universitari de Lingüística Aplicada (IULA), UPF.  
  👉 Obra clave para entender qué es un término, cómo se conceptualiza y cómo se usa en comunicación especializada.  
  🔗 https://www.upf.edu/web/iula/publicacions

- **Cabré, M. T. (2003). “Theories of terminology: Their description, prescription and explanation”.**  
  *Terminology*, 9(2).  
  🔗 https://doi.org/10.1075/term.9.2.03cab  
  👉 Texto fundamental para conectar teoría terminológica y enfoques computacionales.

---

### 📖 2. Terminología computacional y extracción automática de términos

#### 🔹 Introducciones accesibles
- **Daille, B. (2017). “Term Extraction”.**  
  En *Handbook of Natural Language Processing* (2nd ed.).  
  🔗 https://hal.science/hal-01542118  
  👉 Visión clara de métodos basados en frecuencia, patrones y estadística.

- **Pazienza, M. T., Pennacchiotti, M., & Zanzotto, F. M. (2005). “Terminology extraction: An analysis of linguistic and statistical approaches”.**  
  *Knowledge Mining*, Springer.  
  🔗 https://doi.org/10.1007/11549408_1  
  👉 Muy útil para entender por qué se combinan filtros lingüísticos y frecuenciales.

---

### 📖 3. Lingüística de corpus aplicada a terminología

- **McEnery, T. & Hardie, A. (2012). *Corpus Linguistics: Method, Theory and Practice*.**  
  Cambridge University Press.  
  🔗 https://doi.org/10.1017/CBO9780511981395  
  👉 Capítulos sobre frecuencia, n-gramas y comparación de corpus muy relevantes para esta práctica.

- **Biber, D., Conrad, S., & Reppen, R. (1998). *Corpus Linguistics: Investigating Language Structure and Use*.**  
  Cambridge University Press.  
  🔗 https://doi.org/10.1017/CBO9780511804489  
  👉 Base teórica sólida para justificar el uso de frecuencia relativa y corpus de referencia.

---

### 📊 4. Métodos basados en frecuencia y comparación de corpus

- **Ahmad, K., Gillam, L., & Tostevin, L. (1999). “University of Surrey participation in TREC-8: Weirdness indexing for logical document extrapolation and retrieval”.**  
  🔗 https://trec.nist.gov/pubs/trec8/papers/surrey.pdf  
  👉 Artículo clásico donde se introduce la idea de *weirdness* como medida comparativa.

- **Kilgarriff, A. (2001). “Comparing corpora”.**  
  *International Journal of Corpus Linguistics*.  
  🔗 https://www.sketchengine.eu/wp-content/uploads/Comparing-Corpora.pdf  
  👉 Texto fundamental para entender por qué y cómo comparar corpus general vs. especializado.

---

### 🎥 5. Vídeos y recursos audiovisuales (introductivos y claros)

- **Introducción a la Lingüística de Corpus (UNED)**  
  🎥 https://www.youtube.com/watch?v=Q8qZr9Kzq2M  
  👉 Explica frecuencia, concordancias y corpus de forma accesible.

- **Keyword in Context (KWIC) explained**  
  🎥 https://www.youtube.com/watch?v=8K3l2kY9G3U  
  👉 Muy útil para entender la parte de mini-glosario y validación contextual.

- **Term extraction and terminology management (WIPO)**  
  🎥 https://www.youtube.com/watch?v=7VxQe9lJ4lA  
  👉 Visión aplicada de la terminología en contextos profesionales.

---

### 🧰 6. Herramientas reales de extracción terminológica (para explorar)

- **TermoStat**  
  🔗 http://termostat.ling.umontreal.ca/  
  👉 Herramienta clásica basada en comparación de corpus.

- **Sketch Engine (Keywords & term extraction)**  
  🔗 https://www.sketchengine.eu/  
  👉 Plataforma profesional para análisis de corpus y terminología.

- **AntConc** (gratuito, muy usado en docencia)  
  🔗 https://www.laurenceanthony.net/software/antconc/  
  👉 Ideal para practicar concordancias, frecuencias y keywords.

---

### 🧠 7. Para ir más allá (sin perder interpretabilidad)

- **Incorporar lematización y PoS**  
  spaCy (documentación):  
  🔗 https://spacy.io/usage/linguistic-features

- **TF-IDF explicado de forma intuitiva**  
  🔗 https://scikit-learn.org/stable/modules/feature_extraction.html#tfidf-term-weighting

- **Evaluación de extracción terminológica**  
  Bonin et al. (2018):  
  🔗 https://aclanthology.org/L18-1556/  

---

### 🎓 Nota final para el alumnado
> La extracción automática de términos **no sustituye** al especialista,  
> pero es una herramienta poderosa para **explorar, priorizar y justificar** decisiones terminológicas a partir de datos reales.

Estos recursos te permitirán conectar **teoría terminológica**, **lingüística de corpus** y **PLN aplicado**, que es exactamente el objetivo de esta unidad.

# Ampliación opcional: conservar "de" dentro de términos (más realista)

En terminología en español, es común que un término multi-palabra incluya:
- “de”, “del”, “la”, “en”…

Ejemplos:
- *modelo de lenguaje*
- *procesamiento del lenguaje natural*
- *extracción de términos*

Una estrategia simple:
- **No eliminar stopwords** al crear n-gramas,
- pero sí filtrar:
  - n-gramas que empiecen o terminen con stopword
  - y mantener stopwords en el interior

In [24]:
# Tokenizamos SIN eliminar stopwords
tokens_esp_raw = []
for doc in corpus_especializado:
    tokens_esp_raw.extend(simple_tokenize(doc))

tokens_gen_raw = []
for doc in corpus_general:
    tokens_gen_raw.extend(simple_tokenize(doc))

N_esp_raw = len(tokens_esp_raw)
N_gen_raw = len(tokens_gen_raw)

freq2_esp_raw = count_ngrams(tokens_esp_raw, 2)
freq3_esp_raw = count_ngrams(tokens_esp_raw, 3)

freq2_gen_raw = count_ngrams(tokens_gen_raw, 2)
freq3_gen_raw = count_ngrams(tokens_gen_raw, 3)

def ngram_good_edges(ng_text: str, stopwords=STOPWORDS_ES) -> bool:
    toks = ng_text.split()
    # No queremos que empiece o termine con stopword
    return (toks[0] not in stopwords) and (toks[-1] not in stopwords)

cand2_raw = filter_by_min_freq(freq2_esp_raw, min_freq=2)
cand3_raw = filter_by_min_freq(freq3_esp_raw, min_freq=2)

# filtramos por bordes
cand2_raw = {t:f for t,f in cand2_raw.items() if ngram_good_edges(t)}
cand3_raw = {t:f for t,f in cand3_raw.items() if ngram_good_edges(t)}

df_bi_raw = compute_weirdness(cand2_raw, freq2_gen_raw, N_esp_raw, N_gen_raw)
df_tri_raw = compute_weirdness(cand3_raw, freq3_gen_raw, N_esp_raw, N_gen_raw)

display(df_bi_raw.head(10))
display(df_tri_raw.head(10))

,term,freq_esp,rel_esp,freq_gen,rel_gen,weirdness
0,etiquetado morfosintáctico,4,0.013072,0,0.0,1.307190e+07
1,concordancias kwic,4,0.013072,0,0.0,1.307190e+07
2,frecuencia relativa,3,0.009804,0,0.0,9.803922e+06
3,corpus especializado,2,0.006536,0,0.0,6.535948e+06

,term,freq_esp,rel_esp,freq_gen,rel_gen,weirdness
0,lingüística de corpus,5,0.016340,0,0.0,1.633987e+07
1,análisis de colocaciones,4,0.013072,0,0.0,1.307190e+07
2,corpus un corpus,3,0.009804,0,0.0,9.803922e+06
3,corpus los ngramas,2,0.006536,0,0.0,6.535948e+06